import { useEffect, useRef, useState, useCallback } from 'react'
import type { IMessage, StompSubscription } from '@stomp/stompjs'
import { createStompClient } from '../services/stompClient'

export interface UseWebSocketResult {
  connected: boolean
  subscribe: (destination: string, callback: (message: IMessage) => void) => string
  unsubscribe: (id: string) => void
}

/**
 * useWebSocket — connects to the STOMP/SockJS endpoint on mount and
 * disconnects on unmount.  Auto-reconnect is handled by the Client
 * (5s reconnect delay set in createStompClient).
 *
 * Returns helpers to subscribe/unsubscribe to STOMP destinations.
 * Subscription IDs are stable strings generated by the hook; the caller
 * passes the same ID back to unsubscribe.
 */
export function useWebSocket(): UseWebSocketResult {
  const [connected, setConnected] = useState(false)

  // Map of subscription-id → StompSubscription so we can unsubscribe by ID.
  const subsRef = useRef<Map<string, StompSubscription>>(new Map())

  // Pending subscriptions requested before the client connected.
  // Shape: [destination, callback, id]
  const pendingRef = useRef<Array<[string, (msg: IMessage) => void, string]>>([])

  const clientRef = useRef(createStompClient())
  const idCounterRef = useRef(0)

  useEffect(() => {
    const client = clientRef.current

    client.onConnect = () => {
      setConnected(true)

      // Flush pending subscriptions accumulated before connect.
      for (const [dest, cb, id] of pendingRef.current) {
        const sub = client.subscribe(dest, cb)
        subsRef.current.set(id, sub)
      }
      pendingRef.current = []
    }

    client.onDisconnect = () => {
      setConnected(false)
    }

    client.onStompError = (frame) => {
      console.error('[STOMP] Error:', frame.headers['message'])
      setConnected(false)
    }

    client.activate()

    return () => {
      // Copy refs into local variables so the cleanup closes over stable values.
      // eslint-disable-next-line react-hooks/exhaustive-deps
      const subs = subsRef.current
      const pending = pendingRef.current

      // Unsubscribe all active subscriptions before deactivating.
      subs.forEach((sub) => {
        try {
          sub.unsubscribe()
        } catch {
          // Ignore — connection may already be gone.
        }
      })
      subs.clear()
      pending.length = 0
      client.deactivate()
    }
  }, [])

  const subscribe = useCallback((destination: string, callback: (message: IMessage) => void): string => {
    const id = `sub-${++idCounterRef.current}`
    const client = clientRef.current

    if (client.connected) {
      const sub = client.subscribe(destination, callback)
      subsRef.current.set(id, sub)
    } else {
      // Queue for flush on connect.
      pendingRef.current.push([destination, callback, id])
    }

    return id
  }, [])

  const unsubscribe = useCallback((id: string): void => {
    const sub = subsRef.current.get(id)
    if (sub) {
      try {
        sub.unsubscribe()
      } catch {
        // Ignore — may already be disconnected.
      }
      subsRef.current.delete(id)
    }
    // Also remove from pending if not yet connected.
    pendingRef.current = pendingRef.current.filter(([, , pendingId]) => pendingId !== id)
  }, [])

  return { connected, subscribe, unsubscribe }
}
